// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/zhi/Program/GoProgram/src/github.com/feiquan123/algorithm/cgo/ctype/qsort/go/v1/qsort/qsort.go:1:1
package qsort

/* 
#include <stdlib.h>

typedef int (*qsort_cmp_func_t) (const void* a, const void* b);  // qsort_cmp_func_t 比较函数定义
*/
import _ "unsafe"
import "unsafe"

type CompareFunc  /*line :11:18*/_Ctype_qsort_cmp_func_t /*line :11:36*/

// 调用 stdlib.h 中的 qsort
// void	 qsort(void *__base, size_t __nel, size_t __width,
//	int (* _Nonnull __compar)(const void *, const void *));
func Sort(base unsafe.Pointer, num, size int, cmp CompareFunc) {
	func() { _cgo0 := /*line :17:10*/base; var _cgo1 _Ctype_size_t = _Ctype_size_t(num); var _cgo2 _Ctype_size_t = _Ctype_size_t(size); var _cgo3 *[0]byte = _Ctype_qsort_cmp_func_t(cmp); _cgoCheckPointer(_cgo0, nil); _Cfunc_qsort(_cgo0, _cgo1, _cgo2, _cgo3); }()
}