// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/zhi/Program/GoProgram/src/github.com/feiquan123/algorithm/cgo/ctype/func/CCallGo/main.go:1:1
package main

/*
// 函数签名
int sum(int a, int b);
*/
import _ "unsafe"

//export sum
func sum(a, b  /*line :10:15*/_Ctype_int /*line :10:20*/)  /*line :10:22*/_Ctype_int /*line :10:27*/ {
	return a + b
}

func main() {}
