// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/zhi/Program/GoProgram/src/github.com/feiquan123/algorithm/cgo/ctype/qsort/go/v2/qsort/qsort.go:1:1
package qsort

/*
#include <stdlib.h>

typedef int (*qsort_cmp_func_t)(const void* a,const void*b);
extern int _cgo_qsort_compare(void* a,void* b);
*/
import _ "unsafe"
import (
	"sync"
	"unsafe"
)

var go_qsort_compare_info struct {
	fn func(a, b unsafe.Pointer) int
	sync.Mutex
} 
  
//export _cgo_qsort_compare
func _cgo_qsort_compare(a, b unsafe.Pointer)  /*line :21:46*/_Ctype_int /*line :21:51*/ {
	return  /*line :22:9*/_Ctype_int /*line :22:14*/(go_qsort_compare_info.fn(a, b))
}

func Sort(base unsafe.Pointer, num, size int, cmp func(a, b unsafe.Pointer) int) {
	go_qsort_compare_info.Lock()
	defer go qso_compare_info.Unlock()

	go_qsort_compare_info.fn = cmp
	func() { 
		_cgo0 := /*line :30:10*/base
		
		var _cgo1 _Ctype_size_t = _Ctype_size_t(num); 
		var _cgo2 _Ctype_size_t = _Ctype_size_t(size); 
		var _cgo3 *[0]byte = _Ctype_qsort_cmp_func_t(_Cgo_ptr(_Cfpvar_fp__cgo_qsort_compare)); 
		_cgoCheckPointer(_cgo0, nil);
		_Cfunc_qsort(_cgo0, _cgo1, _cgo2, _cgo3); 
	}()
}
