// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_int int32

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})
//go:linkname __cgo_go_qsort_compare go_qsort_compare
//go:cgo_import_static go_qsort_compare
var __cgo_go_qsort_compare byte
var _Cfpvar_fp_go_qsort_compare unsafe.Pointer = (unsafe.Pointer)(unsafe.Pointer(&__cgo_go_qsort_compare))

//go:cgo_export_dynamic go_qsort_compare
//go:linkname _cgoexp_45eb936b1347_go_qsort_compare _cgoexp_45eb936b1347_go_qsort_compare
//go:cgo_export_static _cgoexp_45eb936b1347_go_qsort_compare
func _cgoexp_45eb936b1347_go_qsort_compare(a *struct {
		p0 unsafe.Pointer
		p1 unsafe.Pointer
		r0 _Ctype_int
	}) {
	a.r0 = go_qsort_compare(a.p0, a.p1)
}
